version: "3.9"

services:
  libreria:
    build: .
    container_name: libreria_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file:/data/libreria_db
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EXTERNAL_API_BOOKS_URL: https://my-json-server.typicode.com/Gabriel-Arriola-UTN/libros/books
    volumes:
      - h2_data:/data

volumes:
  h2_data:
